const products: productType[] = [
  {
    name: "لامبورگینی",
    _id: "324234234",
    image: "/images/hero3.jpg",
    companyName: "alpha",
    madeDate: "2020",
    price: "100000$",
    description: "این متن صرفا جهت نمایش و به صورت غیر تصادقی تولید شده است",
    option: ["خودران", "دنده اتومات"],
    color: "قرمز",
    quantity: 1,
  },
  {
    name: "فراری",
    _id: "324234sdf234",
    image: "/images/hero2.jpg",
    companyName: "Beta",
    madeDate: "2020",
    price: "120000$",
    description: "این متن صرفا جهت نمایش و به صورت غیر تصادقی تولید شده است",
    option: ["دنده اتومات"],
    color: "آبی",
    quantity: 1,
  },
  {
    name: "بی ام وی",
    _id: "32423423432234",
    image: "/images/hero1.jpg",
    companyName: "teta",
    madeDate: "2010",
    price: "80000$",
    description: "این متن صرفا جهت نمایش و به صورت غیر تصادقی تولید شده است",
    option: ["بدون آپشن"],
    color: "زرد",
    quantity: 1,
  },
  {
    name: "تویاتا",
    _id: "324234223434r32r34",
    image: "/images/hero.jpg",
    companyName: "segma",
    madeDate: "2021",
    price: "120000$",
    description: "این متن صرفا جهت نمایش و به صورت غیر تصادقی تولید شده است",
    option: ["دنده اتومات", "آفرود"],
    color: "سفید",
    quantity: 0,
  },
];

export default products;
